// <auto-generated />
using BiblioRepo.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiblioRepo.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BiblioRepo.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Psychology & Mind"
                        },
                        new
                        {
                            Id = 2,
                            Title = "History"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Romance"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Crime, Thriller & Mystery"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Action & Adventure"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
